# Generated by Django 5.0.2 on 2024-02-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='password',
            new_name='passw',
        ),
        migrations.RenameField(
            model_name='detail',
            old_name='phoneno',
            new_name='phone',
        ),
    ]
