# Generated by Django 5.0.2 on 2024-02-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_details_detail_rename_password_detail_passw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=16)),
                ('productprice', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('images', models.FileField(upload_to='')),
            ],
        ),
    ]
