# Generated by Django 5.0.2 on 2024-03-05 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='password_reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.detail')),
            ],
        ),
    ]
