# Generated by Django 5.0.2 on 2024-03-05 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_password_reset'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='password_reset',
            new_name='PasswordReset',
        ),
    ]
