# Generated by Django 5.0.2 on 2024-03-05 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_password_reset_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='user_details',
            new_name='user',
        ),
    ]
