# Generated by Django 5.0.2 on 2024-03-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_user_details_passwordreset_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sub',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
