# Generated by Django 5.0.2 on 2024-03-27 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.detail')),
            ],
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
