# Generated by Django 5.0.2 on 2024-04-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_product_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
