# Generated by Django 5.0.2 on 2024-04-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_booking_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
