# Generated by Django 5.0.2 on 2024-04-24 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_quantity', models.IntegerField(default=1)),
                ('wishlist_product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.product')),
                ('wishlist_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.detail')),
            ],
        ),
    ]
