# Generated by Django 5.0.2 on 2024-05-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
